---
# Install Kubernetes

# Distribution-specific tasks:
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: install ebtables and kubeadm
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - ebtables
    - kubeadm
